// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2xaRROu6AGBfTJqFoKJAfr3A3VJ4Tbmk',
    appId: '1:713448478174:web:cb0d8734de0f8b6a32b94f',
    messagingSenderId: '713448478174',
    projectId: 'hushbuddy-9fdbb',
    authDomain: 'hushbuddy-9fdbb.firebaseapp.com',
    storageBucket: 'hushbuddy-9fdbb.firebasestorage.app',
    measurementId: 'G-MYMF02Q25V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHLxovASVVL7HhoXW0fG2KSujLdRmPwE',
    appId: '1:713448478174:android:6ff2a49192cc02c932b94f',
    messagingSenderId: '713448478174',
    projectId: 'hushbuddy-9fdbb',
    storageBucket: 'hushbuddy-9fdbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Z-K_nItVvK9_U6TTdjoLp9GlLcSJbR8',
    appId: '1:713448478174:ios:c99c5ec5ac81933432b94f',
    messagingSenderId: '713448478174',
    projectId: 'hushbuddy-9fdbb',
    storageBucket: 'hushbuddy-9fdbb.firebasestorage.app',
    iosBundleId: 'com.example.babybeacon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Z-K_nItVvK9_U6TTdjoLp9GlLcSJbR8',
    appId: '1:713448478174:ios:c99c5ec5ac81933432b94f',
    messagingSenderId: '713448478174',
    projectId: 'hushbuddy-9fdbb',
    storageBucket: 'hushbuddy-9fdbb.firebasestorage.app',
    iosBundleId: 'com.example.babybeacon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2xaRROu6AGBfTJqFoKJAfr3A3VJ4Tbmk',
    appId: '1:713448478174:web:61ccfa1f4aacde1a32b94f',
    messagingSenderId: '713448478174',
    projectId: 'hushbuddy-9fdbb',
    authDomain: 'hushbuddy-9fdbb.firebaseapp.com',
    storageBucket: 'hushbuddy-9fdbb.firebasestorage.app',
    measurementId: 'G-YLT7671P2G',
  );

}